image: docker:latest

stages:
  - docker

build_image:
  stage: docker
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/kontext/documentation .
    - docker push registry.gitlab.com/kontext/documentation
  only:
    - master
    - docker-build

